osrgroup/msadoc

server/src/database/db-config.service.ts

At the moment, e2e tests fail because of errors like this:
```
ERROR [ExceptionsHandler] No metadata for "ServiceDocOrm" was found.
```
This PR uses a different mechanism for loading entities in order to (temporarily) fix this. Unfortunately, I don't know enough about NestJS so I cannot say if the mechanism has any singificant downsides. According to the documentation on https://docs.nestjs.com/techniques/database, it has the following problem:
```
Note that entities that aren't registered through the forFeature() method, but are only referenced from the entity (via a relationship), won't be included by way of the autoLoadEntities setting. 
```
I simply don't know if that is something we care about at the moment. So my suggestion is that we:
1. use the new loading mechanism for now, so …

Fix e2e tests by using a different entities loading mechanism

---

README.md
docs/msadoc.md
server/src/database/migrations.config.ts
server/src/database/migrations/1662991669104-ServiceDocsTags.ts
server/src/database/migrations/1662991810846-ServiceDocsRenameProvidedAPIs.ts
server/src/service-docs/service-doc.dto.ts
server/src/service-docs/service-doc.orm.ts
server/src/service-docs/service-docs.service.spec.ts
server/src/service-docs/service-docs.service.ts
server/test/service-docs.e2e-spec.ts

* Add array field `tags` for tagging a service-doc. Will be later used in UI to filter.
* Fix migrations path to generate migrations via typeorm.
* Fix fields `providedAPIs`, `taskBoard` and `developmentDocumentation` which were handled incorrectly in persistance.

Introduce tags to service-doc

---

frontend/.vscode/snippets.code-snippets
frontend/package-lock.json
frontend/package.json
frontend/src/app.tsx
frontend/src/components/login-page/index.tsx
frontend/src/components/login-page/login-page.tsx
frontend/src/components/main-page/auth-tokens-page/auth-tokens-page.tsx
frontend/src/components/main-page/auth-tokens-page/index.tsx
frontend/src/components/main-page/groups-tree-page/groups-tree-page.tsx
frontend/src/components/main-page/groups-tree-page/index.tsx
frontend/src/components/main-page/index.tsx
frontend/src/components/main-page/left-menu.tsx
frontend/src/components/main-page/main-page.tsx
frontend/src/components/main-page/routes.tsx
frontend/src/components/main-page/services/service-docs-service.tsx
frontend/src/index.tsx
frontend/src/routes.tsx
frontend/src/services/auth-data-service.tsx
frontend/src/services/http-service.tsx
frontend/src/theme/main.scss

This PR is part 3 of #4. The PR contributes the following:
- We now have a Router and 3 pages: `/login`, `/main/groups-tree`, and `/main/auth-tokens` (I honestly was not sure how to call the page where we list the groups, so I just called it GroupsTree for now).
- The pages in `main` all have access to a shared `ServiceDocsService` which contains the current ServiceDocs. So we don't have to perform additional API requests when the user navigates around the `main` pages.
- There is a "Reload Service Docs" button on the bottom left, so users are able to refresh the Service Docs if they want to. To improve the UX, I decided to implement this reloading in a way that component State is not lost when the user presses the button.
- We now use MaterialUI (MUI) for the frontend. This has one …

Add routing and Material UI

---

frontend/src/app.tsx
frontend/src/components/login-page/login-page.tsx
frontend/src/components/main-page/left-menu.tsx
frontend/src/components/main-page/main-page.tsx
frontend/src/components/main-page/router.tsx
frontend/src/router.tsx
frontend/src/routes.ts
frontend/src/services/http-service.tsx

I noticed a pretty error-prone setup with our router: Whenever we would use functions like `navigate(...)`, we would simply pass a string as the target route. For example, to navigate to the "groups-tree" page, we would say `navigate('/main/groups-tree')`. This is not ideal because it makes refactoring pretty hard and typos cannot be detected during compile-time.
This PR addresses this: In `src/routes.ts`, there are now objects that explicitly define the router paths. To navigate to the aformentioned page, we would now use `navigate(MAIN_PAGE_ROUTES_ABS.groupsTree)`.
You might be wondering why there is an "ABS" at the end. Most of the time, we need the full URL like `/main/groups-tree`. However, when assigning our routes to the React Router, we also need the relative URL like …

Define type-safe routes

---

client-generated/models/CreateServiceDocRequest.ts
client-generated/models/CreateServiceDocResponse.ts
client-generated/models/DeleteServiceDocResponse.ts
client-generated/models/GetServiceDocResponse.ts
server/src/service-docs/service-doc.dto.ts

It seems like the Swagger/OpenAPI generator is not able to automatically determine if a property is optional. Thus, fields like `group` were all typed as `group: string` instead of `group?: string` in the generated client library. This PR fixes this by adding `required: false` to all optional fields.
This was actually pretty surprising, because the server does not seem to complain when you send a request to create a new Service Doc without adding all required properties. @georg-schwarz We should talk about that in a meeting, because it could have security implications.
Now, only the `name` is required (see the red `*`):

Properly annotate optional Service Docs fields

---

frontend/src/components/main-page/groups-tree-page/group-details/group-details.tsx
frontend/src/components/main-page/groups-tree-page/group-details/index.tsx
frontend/src/components/main-page/groups-tree-page/groups-tree-page.tsx
frontend/src/components/main-page/groups-tree-page/router.tsx
frontend/src/components/main-page/groups-tree-page/service-details/index.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx
frontend/src/components/main-page/groups-tree-page/tree/group-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/index.tsx
frontend/src/components/main-page/groups-tree-page/tree/root-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/service-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/tree.tsx
frontend/src/components/main-page/router.tsx
frontend/src/components/main-page/services/service-docs-service.tsx
frontend/src/components/main-page/utils/service-docs-utils.ts
frontend/src/routes.ts

This PR adds a tree view on the left, so that users are now able to easily navigate through the groups and services. For this, a recursive data structure called `ServiceDocsGroup` is created, which contains a group name/identifier, the direct children of the group and the services belonging to the group.
<details>
<summary>Example</summary>
If an identifier like `foo.bar` is used for a group, a data structure like this is created:
``` js
{
childGroups: {
foo: {
name: 'foo',
identifier: 'foo',
childGroups: {
bar: {
name: 'bar',
identifier: 'foo.bar',
childGroups: {},
services: [ /* The service(s) that included the group identifier are stored here. */]
}
},
services: []
}
},
services: [
// The services that don't belong to any group are added here.
]
}
```
This makes it pretty easy to build …

Groups tree basics

---

frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx

This PR removes `JSON.stringify()` from the Service Details page. Instead, we now show some basic information about a service: The name, group, repository, and task board.
Please note that this only affects the Service Details page. On the Group Detail page, we are still showing the `JSON.stringify()` content.
If a particular piece of information is not available, it will simply not be shown in the list (here, the group is missing):

Show basic service details

---

example/extraction.service.msadoc.json
example/graphql-query.service.msadoc.json
example/load.service.msadoc.json
example/notification.service.msadoc.json
example/restful-query.service.msadoc.json
example/scheduler.service.msadoc.json
example/transformation.service.msadoc.json
example/web.client.msadoc.json

When working on #51, I noticed a few typos in the examples:
- It said `providedApis` instead of `providedAPIs` (the same with consumed APIs)
- I noticed a missing slash in an API of the TransformationService. (That has no effect at the moment, but I still wanted to make the examples consistent, so I fixed this as well.)

Fix typos in examples

---

frontend/src/components/main-page/groups-tree-page/group-details/group-details.tsx
frontend/src/components/main-page/groups-tree-page/service-details/dependencies.tsx
frontend/src/components/main-page/groups-tree-page/service-details/dependency-details.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx
frontend/src/components/main-page/groups-tree-page/tree/group-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/root-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/service-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/tree.tsx
frontend/src/components/main-page/services/service-docs-service.tsx
frontend/src/components/main-page/utils/router-utils.ts
frontend/src/components/main-page/utils/service-docs-utils.ts

This PR contributes the following:
- There is now a hook function that allows us to easily fetch the currently selected Service/Group.
- When navigating to a new Service/Group, the items corresponding to the ancestors of the Service/Group in the tree are automatically un-collapsed. This is necessary when programmatically navigating e.g. because the user clicks on a Service in the main view.
- There is now a "Dependencies" section in the main view that lists all provided/consumed APIs and all produced/consumed Events. When a user clicks on an entry, a dialog is shown that shows all other Services that are related to the respective API or Event. When clicking on a Service in this list, the dialog closes and the new Service is selected, so that the user is now able to explore this Service in …

Service dependencies

---

frontend/src/components/main-page/utils/router-utils.ts
frontend/src/services/http-service.tsx

This PR fixes token refreshing in the frontend. I initially thought that token refreshing was broken on the backend. But as it turns out, I should have had a closer look at the tests. 😄  The reason: The frontend currently only sends the refresh token in the body. But it seems like the refresh token needs to be sent both in the body and in the auth header. 
This PR fixes this by sending the refresh token both in the body and in the header.
Also, this PR removes a misleading `console.warn()` that would appear e.g. after logging in. Since this is such a small change, I decided to include it in this PR as well.

Frontend token refreshing

---

server/src/api-keys/api-keys.dto.ts
server/src/service-docs/service-doc.dto.ts
server/src/utils/class-validators.ts
server/test/service-docs.e2e-spec.ts

Closes #58
* The `class-validators` library seems to really need all those redundant `@IsString` annotations otherwise it also allows numbers, objects, arrays, etc. - at least in the configuration we use it.
* DTO models can be really crowded and confusing with all these annotations, esp. if done redundantly for API docs as well (swagger decorations)
* You can aggregate decorators by creating your custom decorators that might fix this issue.

Use custom decorators to aggregate multiple annotations

---

frontend/src/components/main-page/groups-tree-page/group-details/group-details.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx

When clicking on the "Repository" or "Task Board" list item in the service details view, the respective URL is now opened. Originally, users would have to manually copy&paste these URLs in order to open them.
Also, this PR fixes some minor semantic inconsistencies.
One thing to note: I always render a `<ListItemButton` element, even if the link is not openable. This has the downside that, when hovering this element, the user might always get the impression that it is clickable (even if the link is invalid). This is probably not ideal for UX, but to avoid an overly complex implementation, I decided to do it like this for now.

Make URLs clickable

---

frontend/src/components/main-page/groups-tree-page/common/dependencies/dependencies.tsx

This PR implements the change requested in #67: When viewing a service, the heading of the Dependencies component now says "Service Dependencies". And when viewing a group, the heading now says "Aggregated Dependencies".

Refactor the dependencies headings

---

frontend/src/components/main-page/groups-tree-page/common/dependencies/dependencies.tsx
frontend/src/components/main-page/groups-tree-page/common/dependencies/dependency-details-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/group-item.tsx

I noticed that, in multiple places, elements were not sorted by their name:
- In the tree view on the left, both services and groups were just displayed in a random order.
- In the "Dependencies" component, the APIs and Events were also just displayed in a random order.
- When clicking on one of the APIs/Events, the shown related Services were also displayed in a random order.
This PR fixes this by sorting these elements by their name.

Sort various elements

---

example/web.client.msadoc.json

I have noticed that there is a typo in the example for the WebService. This PR fixes this typo.

Fix a typo in the example request for the WebService

---

frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/graph-hops.ts
frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/sankey-data.ts
frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/visualization-config.tsx
frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/visualization-modal.tsx
frontend/src/components/main-page/service-docs-tree.ts
frontend/src/components/main-page/utils/service-docs-tree-utils.ts
frontend/src/utils/set.ts

This PR makes it possible to remove all entries from the Sankey Diagram that are "unrelated" to the Pivot Node. Or, in other words: The user can now remove all nodes and links that are grey.
After I had implemented this, I noticed a bug in our Sankey Diagram: Some nodes would show up as being related to our Pivot Node, even if they weren't. This happened in a situation like this:
```
ServiceA --> Event --> PivotService
|
+ ----> ServiceB
```
I expected only ServiceA and the PivotService to show up when filtering out the unrelated nodes. However, ServiceB would also show up (and ServiceB would also get a color, which means that the system has indeed assumed that ServiceB can be reached in 2 hops from the PivotService).
The reason for this was because when calculating the Hops, I did not …

Filter unrelated entries

---

frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/sankey-link-tooltip.tsx
frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/visualization-modal.tsx

This PR implements the features described in #65: When hovering a link, a human-readable string is shown like "Service X consumes API Y".
There are quite a lot of cases we have to distinguish, which led to the rather long if-cascade. I did not find a better maintainable solution for this (at least none that is still readable), so I decided to go for this solution. If you have an idea for a better solution, then I would be really happy to implement that 😃 
One thing that we might consider in the future: Currently, there is no limit regarding how many services are listed in the tooltip. If we have a use case where there are really many services that provide a particular API/Event, then the tooltip might become huge. We could say something like `Group "my-group" (services "ServiceA", …

Refine the Sankey link tooltips to show a more detailed explanation of the respective connection

---

frontend/src/components/main-page/groups-tree-page/common/data-container.tsx
frontend/src/components/main-page/groups-tree-page/common/dependencies/dependencies.tsx
frontend/src/components/main-page/groups-tree-page/common/responsibilities/group-responsibilities.tsx
frontend/src/components/main-page/groups-tree-page/common/responsibilities/index.ts
frontend/src/components/main-page/groups-tree-page/common/responsibilities/responsibilities.tsx
frontend/src/components/main-page/groups-tree-page/common/responsibilities/responsible-details.tsx
frontend/src/components/main-page/groups-tree-page/common/responsibilities/service-responsibilities.tsx
frontend/src/components/main-page/groups-tree-page/common/responsibilities/team-details.tsx
frontend/src/components/main-page/groups-tree-page/common/tags/tags.tsx
frontend/src/components/main-page/groups-tree-page/group-details/group-details.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx

This PR:
- Add a section called "Responsibles" to our service view, and a section called "Aggregated Responsibles" to our group view. When clicking on a Responsible (i.e. a person) or on a team, other services are shown that also list this particular person/team.
- Adds a section called "Documentation" to our service view. When clicking on an entry, the respective URL is opened in a new browser tab.
- Adds enhancements to the general UI design.
Regarding the last point: When implementing the "Responsibles" feature, I noticed that it was kinda hard for the eye to follow which items actually belong to the "Responsibles", and which items are part of the next data group. So I decided to add some visual grouping by adding a pretty prominent shadow, creating a card-like effect. Also, I swapped …

Show responsibles + documentations, improve the general UI design

---

.github/workflows/main.yaml
client-generated/package.json
client-generator/package.json
frontend/README.md
frontend/package.json
frontend/src/components/main-page/groups-tree-page/common/dependencies/visualization/visualization-modal.tsx
frontend/src/components/main-page/groups-tree-page/filter/apply-filter.ts
frontend/src/components/main-page/groups-tree-page/filter/filter-dialog.tsx
frontend/src/components/main-page/groups-tree-page/filter/index.ts
frontend/src/components/main-page/groups-tree-page/filter/models.ts
frontend/src/components/main-page/groups-tree-page/filter/parse-query.test.ts
frontend/src/components/main-page/groups-tree-page/filter/parse-query.ts
frontend/src/components/main-page/groups-tree-page/groups-tree-page.tsx
frontend/src/components/main-page/groups-tree-page/router.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx
frontend/src/components/main-page/service-docs-tree.ts
frontend/src/components/main-page/services/service-docs-service.tsx
frontend/src/models/result.ts
frontend/src/setupTests.ts
package-lock.json
package.json

This PR is pretty huge. Its main purpose is to introduce filtering. While implementing this, I noticed a few small bugs/inconsistencies, which I decided to fix right away.
Filtering can be done using a custom "filter language". This probably needs a bit more explaination.
Filter queries are written using `key:value` pairs such as `name:foo`. The `key` may be one of the following:
<details>
- name
- tag
- group
- repository
- taskboard
- providedapi
- consumedapi
- publishedevent
- subscribedevent
- developmentdocumentation
- deploymentdocumentation
- apidocumentation
- responsibleteam
- responsible
</details>
Casing does not matter, so for example `name:foo` and `NAME:foo` is equivalent.
You can use quotes if you need to use whitespace for a value: `name:"some name"`
Currently, the value …

Implement filtering

---

frontend/src/components/main-page/groups-tree-page/groups-tree-page.tsx
frontend/src/components/main-page/groups-tree-page/router.tsx
frontend/src/components/main-page/groups-tree-page/tree/group-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/root-item.tsx
frontend/src/components/main-page/groups-tree-page/tree/service-item.tsx

Currently, when a new service/group is selected, the main content (i.e. the part that displays the service/group details) is not scrolled to the top. This is pretty counter-intuitive: Normally, you expect that a page is scrolled to the top whenever you navigate to a new piece of content.
To try this out: Open any service (ideally one with a lot of content), scroll down, and then select another service (again ideally one with a lot of content). You will notice that the scroll position remains the same, which means that we basically "start in the middle of the service details".
This PR makes the main content scroll to the top whenever a new item is selected in the tree. Unfortunately, I had to disable smooth scrolling in the tree because of a Chrome bug, see …

Scroll the main content to the top when a different Tree Item is selected

---

frontend/src/components/main-page/groups-tree-page/filter/filter-dialog.tsx
frontend/src/components/main-page/groups-tree-page/filter/syntax-documentation.tsx

This PR adds a section called "Syntax Documentation" to the Filter dialog. The section is shown when pressing the "?" button. It includes information about the filter syntax, so that users can get familiar with this syntax.

Add a 'Syntax Documentation' section

---

frontend/src/components/main-page/graph-page/dependency-graph-view.tsx

Closes #109.
Builds on #108. Only merge after!
Added a download button that downloads the current view of the dependency graph.
Better diff: https://github.com/osrgroup/msadoc/compare/105-configure-graph-depth...109-download-graph-image

Download graph image

---

frontend/src/components/main-page/groups-tree-page/service-details/extension-fields.tsx
frontend/src/components/main-page/groups-tree-page/service-details/service-details.tsx

This PR adds the missing part from #18: Extension fields are now shown in the frontend (in a pretty generic way). If no extension fields are defined, then the card is not shown at all.

Show extension fields in the frontend

---

frontend/src/components/login-page/login-page.tsx
frontend/src/components/main-page/graph-page/cytoscape-builder.ts
frontend/src/components/main-page/graph-page/dependency-graph-view.tsx
frontend/src/components/main-page/groups-tree-page/router.tsx
frontend/src/models/api.ts
frontend/src/services/http/api-keys.tsx
frontend/src/services/http/auth.tsx
frontend/src/services/http/http-base.tsx
frontend/src/services/http/service-docs.tsx

This PR adds various small improvements:
- I have found duplicate code in the http services. There is now a function called `httpService.performRegularHttpRequest()` which takes care of this. *
- The design of the error message that is shown when a login fails is now improved: Originally, a red string would be shown, now we show a proper `<Alert />`.
- The PR also fixes a bug in the graph that would pull it to the center whenever `setState()` was called somewhere. **
- On our ServiceDocsDetails/GroupDetails page, we have a mechanism that scrolls the page to the top whenever the selected Service/Group changes. However, the page would sometimes be scrolled to the top even though the Service/Group did not change. This was because we listened for Props changes as well. I have fixed this to …

Add various improvements

---

frontend/src/components/main-page/service-docs-explorer-page/group-details/dependency-graph/graph.tsx
frontend/src/index.tsx

Closes #116. Since Cytoscape prints a warning when reducing the sensitivity, I decided to monkey-patch `console.warn()` in order to silence the warning.
@georg-schwarz Could you try whether the new settings are ok with your mouse? On my side, zooming now feels pretty "natural", but this could be related to my setup.

Reduce the mouse wheel sensitivity

---

frontend/src/components/main-page/service-docs-explorer-page/group-details/group-details.tsx

I noticed that when there are no Service Docs (e.g. because the filter is not matching anything), the page looks like this:
So we have a lot of boxes saying "0 foo, 0 bar, ...", and the graph is completely blank.
Certainly, we could add case distinctions in all of the cards that say "there is currently nothing to show". But the much simpler solution is to simply hide the right content completely:
Given that we already have the warning message on the left ("No Service Docs found"), I believe/hope this is sufficient for now.

Hide the group details when there are no Service Docs

---

frontend/src/components/main-page/service-docs-explorer-page/filter/apply-filter.ts
frontend/src/components/main-page/service-docs-explorer-page/filter/models.ts
frontend/src/components/main-page/service-docs-explorer-page/filter/parse-query.ts
frontend/src/components/main-page/service-docs-explorer-page/filter/syntax-documentation.tsx

This PR implements the features described in #133: It is now possible to filter by extension fields. 
For instance, to find all Service Docs where there is an extension field called "deployed" that is `true`, use the following query:
```
extensions.deployed:true
```
Two notes:
- As you know, our queries contain `key:value` pairs. Internally, we now distinguish "Literal Keys" and "Extensions Keys" (plural form intended). A Literal Key is what we have used before, like "name" or "group". An Extensions Key is a key in the format "extensions.something". In the internal data structure, we simply store the key as a string. To check whether we have a Literal Key or an Extensions Key, there is a function that basically just checks if the string starts with "extensions." or not.
- It was necessary …

Make it possible to filter by Extension Field

---

docs/msadoc.md
example/extraction.service.msadoc.json
example/graphql-query.service.msadoc.json
example/load.service.msadoc.json
example/notification.service.msadoc.json
example/restful-query.service.msadoc.json
example/scheduler.service.msadoc.json
example/transformation.service.msadoc.json
example/web.client.msadoc.json
schemas/service-doc.json

Closes #135. Additionally, this PR fixes a few minor errors in the documentation (e.g. the documentation used `` ` `` instead of `'` in the word ``microservice`s``, which made the Markdown formatting break). 
I decided to create a folder called "schemas". If, in the future, we want to add additional schemas (e.g. because we introduce a JSON file to describe groups or the like), we can add it to this folder.
In the schema, you will see that I used "description" and "markdownDescription". The first one is the official standard. The latter is a VSCode-specific one that allows us to use Markdown. See https://code.visualstudio.com/docs/languages/json#_use-rich-formatting-in-hovers
Forgetting to define a name:
Wrong spelling of a property:

Add JSON Schema

---

frontend/src/components/main-page/service-docs-explorer-page/navigator/common/navigator-list-item-button.tsx
frontend/src/components/main-page/service-docs-explorer-page/navigator/responsibles/responsible-item.tsx
frontend/src/components/main-page/service-docs-explorer-page/navigator/responsibles/responsibles.tsx
frontend/src/components/main-page/service-docs-explorer-page/navigator/teams/team-item.tsx
frontend/src/components/main-page/service-docs-explorer-page/navigator/teams/teams.tsx

Closes #132: When viewing the Responsibles or the Team list, we originally did not show Service Docs that do not have a Responsible/Team. Now, there is a special item that is always shown at the end of the list. This item contains all Services that do not have a Responsible/Team.

Show Services without a Responsible/Team

---

frontend/src/components/main-page/service-docs-explorer-page/navigator/navigator.tsx
frontend/src/components/main-page/service-docs-explorer-page/navigator/services-list.tsx

Closes #147
This PR adds a plain list view for Service Docs as described in #147.

Add a plain list view for Service Docs

---

frontend/src/components/main-page/service-docs-explorer-page/filter/filter-dialog.tsx
frontend/src/components/main-page/service-docs-explorer-page/search/index.ts
frontend/src/components/main-page/service-docs-explorer-page/search/search-dialog.tsx
frontend/src/components/main-page/service-docs-explorer-page/service-docs-explorer-page.tsx

This PR implements a simple search dialog as described in #154.
Two notes:
- The search is affected by the Filter. So if the user has defined a filter, then the list of services shown in the search only includes those matched by the filter.
- At the moment, we perform simple substring matching. In the future, we could think about adding fuzzy searching capabilities using a library like [FuseJS](https://fusejs.io/).

Implement a simple search dialog

---

frontend/src/components/main-page/service-docs-explorer-page/filter/apply-filter.ts

At the moment, when entering `name:serv` into the filer, Services like "FooService" are also found. This is because the Regex we build does not make sure the entire string is checked (i.e. the Regex does not start with `^` and end with `$`). This PR fixes this issue.

Make sure the filter takes substring positions into account

---

frontend/src/components/main-page/service-docs-explorer-page/group-details/dependency-graph/cytoscape-builder.ts
frontend/src/components/main-page/service-docs-explorer-page/group-details/dependency-graph/edge-details-popover.tsx
frontend/src/components/main-page/service-docs-explorer-page/group-details/dependency-graph/graph.tsx

When clicking on an edge in the graph, a Popover is now shown. This is roughly as described in #106.
The Popover stays open until the user clicks outside of it. It can also be closed using a "x" button.
At the moment, the Popover only shows the name of the source and target of the edge. In a future PR, we could add additional information. 
I was a bit hesitant when it comes to adding additional information, because I did not know how to deal with cases where there is more than just one Event (or API) for one given pair of source/target nodes. I think the CytoscapeBuilder simply creates multiple edges for this. But they will probably just be rendered on top of each other. So we might need to do some pre-processing here in order to determine which Events/APIs are actually connecting the two …

Show a Popover menu when clicking on an edge

---

frontend/README.md

This PR closes #161.
I also explained that you should open the root of the project (and not the `frontend/` folder), because otherwise, the mentioned VSCode code snippet will not work.

Explain that we are following the Controller Pattern

---

client-generated/package.json
client-generator/package.json
frontend/package.json
package-lock.json
package.json
server/package.json

This PR closes #162 by removing unnecessary "version" fields from all `package.json` files (except for the CLI).

Remove unnecessary "version" fields
